In [ ]:
import nltk
import numpy as np
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from matplotlib import pyplot as plt
import seaborn as sns

dataset = pd.read_csv("/content/Tweets.csv")
dataset.head(15)

,textID,text,selected_text,sentiment
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,088c60f138,my boss is bullying me...,bullying me,negative
3,9642c003ef,what interview! leave me alone,leave me alone,negative
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative
5,28b57f3990,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...,neutral
6,6e0c6d75b1,2am feedings for the baby are fun when he is a...,fun,positive
7,50e14c0bb8,Soooo high,Soooo high,neutral
8,e050245fbd,Both of you,Both of you,neutral
9,fc2cbefa9d,Journey!? Wow... u just became cooler. hehe....,Wow... u just became cooler.,positive
10,2339a9b08b,"as much as i love to be hopeful, i reckon the...","as much as i love to be hopeful, i reckon the ...",neutral
11,16fab9f95b,I really really like the song Love Story by Ta...,like,positive
12,74a76f6e0a,My Sharpie is running DANGERously low on ink,DANGERously,negative
13,04dd1d2e34,i want to go to music tonight but i lost my vo...,lost,negative
14,bbe3cbf620,test test from the LG enV2,test test from the LG enV2,neutral

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punk_tab')

dataset.drop(("textID"),axis=1,inplace=True)
dataset.head(25)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Error loading punk_tab: Package 'punk_tab' not found in
[nltk_data]     index

,text,selected_text,sentiment
0,"I`d have responded, if I were going","I`d have responded, if I were going",neutral
1,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative
2,my boss is bullying me...,bullying me,negative
3,what interview! leave me alone,leave me alone,negative
4,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative
5,http://www.dothebouncy.com/smf - some shameles...,http://www.dothebouncy.com/smf - some shameles...,neutral
6,2am feedings for the baby are fun when he is a...,fun,positive
7,Soooo high,Soooo high,neutral
8,Both of you,Both of you,neutral
9,Journey!? Wow... u just became cooler. hehe....,Wow... u just became cooler.,positive
10,"as much as i love to be hopeful, i reckon the...","as much as i love to be hopeful, i reckon the ...",neutral
11,I really really like the song Love Story by Ta...,like,positive
12,My Sharpie is running DANGERously low on ink,DANGERously,negative
13,i want to go to music tonight but i lost my vo...,lost,negative
14,test test from the LG enV2,test test from the LG enV2,neutral
15,"Uh oh, I am sunburned","Uh oh, I am sunburned",negative
16,"S`ok, trying to plot alternatives as we speak...",*sigh*,negative
17,i`ve been sick for the past few days and thus...,sick,negative
18,is back home now gonna miss every one,onna,negative
19,Hes just not that into you,Hes just not that into you,neutral
20,"oh Marly, I`m so sorry!! I hope you find her...","oh Marly, I`m so sorry!! I hope you find her ...",neutral
21,Playing Ghost Online is really interesting. Th...,interesting.,positive
22,is cleaning the house for her family who is co...,is cleaning the house for her family who is co...,neutral
23,gotta restart my computer .. I thought Win7 wa...,gotta restart my computer .. I thought Win7 wa...,neutral
24,SEe waT I Mean bOuT FoLL0w fRiiDaYs... It`S cA...,SEe waT I Mean bOuT FoLL0w fRiiDaYs... It`S cA...,neutral